dnd_class_description = {
    "Aasimar - Mortals touched by celestial power, often glowing with divine radiance. Natural healers and protectors, guided by an inner celestial spirit.",
    "Genasi (Air, Earth, Fire, Water) - Descendants of mortals and elementals. Air: swift and free-spirited. Earth: tough and stoic. Fire: fiery and passionate. Water: fluid, graceful, and at home in the seas.",
    "Goliath - Towering mountain-dwellers with stone-like resilience. Competitive, hardy, and naturally athletic.",
    "Firbolg - Gentle giant forest guardians. Shy, druidic, with innate magic tied to nature and disguise.",
    "Kenku - Cursed crowfolk who can’t speak normally; they mimic sounds and voices instead. Clever, sneaky, often rogues or spies.",
    "Tabaxi - Catfolk wanderers driven by curiosity. Agile, quick, and obsessed with discovering shiny objects and stories.",
    "Triton - Underwater guardians from the deep seas. Noble, lawful, with water magic and the ability to breathe underwater.",
    "Lizardfolk - Cold-blooded reptilian survivors. Pragmatic, emotionless, and focused on survival instincts above all.",
    "Yuan-ti Pureblood - Snake-like humanoids touched by dark serpentine magic. Cunning, manipulative, often tied to sinister cults.",
    "Orc - Fierce, warlike, and strong. In 5e expansions, they’re more nuanced—honorable warriors rather than just monsters.",
    "Gith (Githyanki, Githzerai) - Alien humanoids freed from mind flayer slavery. Githyanki: raiders and conquerors. Githzerai: monastic philosophers with psionic discipline.",
    "Tortle - Turtlefolk wanderers. Peaceful nomads with natural armor from their shells, often seeking life’s simple joys.",
    "Changeling - Shapeshifters who can alter their appearance at will. Masters of disguise, living between identities.",
    "Kalashtar - Mortal-Quori hybrids, bonded with spirits from the dream realm. Wise, psychic, and serene, but hunted by nightmare entities.",
    "Shifter - Humanoids with lycanthropic heritage. They can briefly 'shift' into more bestial forms, gaining claws, fangs, or heightened senses.",
    "Warforged - Construct soldiers built for war, now seeking purpose. Living constructs of metal and wood, with souls bound to them.",
    "Leonin - Lionfolk from Theros. Proud, courageous, and protective of their prides, with powerful roars and athletic might.",
    "Satyr - Fey goatfolk of revelry and freedom. Mischievous, musical, and lovers of adventure and joy.",
    "Owlin - Owlfolk with silent wings. Stealthy, wise, and mysterious, often drawn to magic or secrets.",
    "Harengon - Rabbitfolk of the Feywild. Energetic, lucky, and fast on their feet, often bouncing into trouble (and out again)."
}


dnd_class = [
    "Aasimar",
    "Genasi (Air, Earth, Fire, Water)",
    "Goliath",
    "Firbolg",
    "Kenku",
    "Tabaxi",
    "Triton",
    "Lizardfolk",
    "Yuan-ti Pureblood",
    "Orc",
    "Gith (Githyanki, Githzerai)",
    "Tortle",
    "Changeling",
    "Kalashtar",
    "Shifter",
    "Warforged",
    "Leonin",
    "Satyr",
    "Owlin",
    "Harengon",
]