dnd_subclasses = {
    "Barbarian": ["Path of the Berserker", "Path of the Totem Warrior"],
    "Bard": ["College of Lore", "College of Valor"],
    "Cleric": ["Knowledge Domain", "Life Domain", "Light Domain", "Nature Domain", "Tempest Domain", "Trickery Domain", "War Domain"],
    "Druid": ["Circle of the Land", "Circle of the Moon"],
    "Fighter": ["Champion", "Battle Master", "Eldritch Knight"],
    "Monk": ["Way of the Open Hand", "Way of Shadow", "Way of the Four Elements"],
    "Paladin": ["Oath of Devotion", "Oath of the Ancients", "Oath of Vengeance"],
    "Ranger": ["Hunter", "Beast Master"],
    "Rogue": ["Thief", "Assassin", "Arcane Trickster"],
    "Sorcerer": ["Draconic Bloodline", "Wild Magic"],
    "Warlock": ["The Archfey", "The Fiend", "The Great Old One"],
    "Wizard": ["School of Abjuration", "School of Conjuration", "School of Divination", 
               "School of Enchantment", "School of Evocation", "School of Illusion", 
               "School of Necromancy", "School of Transmutation"]
}
dnd_subclass_list = [
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
]